### ISSUE TITLE
Right-hand rule error on website examples

### ISSUE THREAD

**Issue by iursevla** [ropensci/geojsonlint#13]
All the examples after LineString, currently present on the website are giving an error.

Line 1: Polygons and MultiPolygons should follow the right-hand rule - Polygon
Line 3: Polygons and MultiPolygons should follow the right-hand rule - Feature
Line 90: Polygons and MultiPolygons should follow the right-hand rule - FeatureCollection
Line 11: Polygons and MultiPolygons should follow the right-hand rule - GeometryCollection example

**Comment by sckott** [comment]
What website are you talking about?  If you're talking about http://geojsonlint.com/ you're in the wrong place - This is the repo for an R package that does geojsonlinting

**Comment by iursevla** [comment]
Yeah sorry for that.
