### ISSUE TITLE
The sample data at http://geojsonlint.com/ doesn't follow the right hand rule

### ISSUE THREAD

**Issue by jdege** [ropensci/geojsonlint#14]
I understand that the GeoJSON standard now requires a right-hand-rule orientation.

But the sample data that is inserted into the test field when you select "Polygon" or "MultiPolygon" from the menu does not.

**Comment by sckott** [comment]
thanks @jdege - are you looking for the github repo for the geojsonlint website?  if so, i'm not sure where that repo is. 

(we probably do need to make sure our examples here have geojson that follows right hand rule 😸 good reminder to check)

**Comment by depuits** [comment]
The site repository can be found at [JasonSanford/geojsonlint.com](https://github.com/JasonSanford/geojsonlint.com)
